apiVersion: v1
kind: Service
metadata:
   name: proj-svc
   namespace: default
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001